irctc automation
Piyush-tft10/seleniumAssignment pull request #1
Opened 2023-07-11 14:45 UTC by Piyush-tft10

please have a look

2023-07-13 16:06 UTC, bawa-onkar-tft requested changes

2023-07-13 16:06 UTC, bawa-onkar-tft commented on src/test/java/PlutoAssignment/IrctcAssignment.java
> +		java.util.Iterator<String> it = handle.iterator();
@Piyush-tft10 what is `it` meaning

2023-07-13 16:06 UTC, bawa-onkar-tft commented on src/test/java/PlutoAssignment/IrctcAssignment.java
> +		List<WebElement> FromLoc = driver.findElements(By.cssSelector(".ui-menu-item"));
@Piyush-tft10 use camel cases `FromLoc`

2023-07-14 11:39 UTC, Piyush-tft10 commented on src/test/java/PlutoAssignment/IrctcAssignment.java
> +		java.util.Iterator<String> it = handle.iterator();
reference variable for iterator class

2023-07-19 15:37 UTC, bawa-onkar-tft approved these changes

2023-07-19 15:47 UTC, merged